---
- name: My first playbook
  hosts: all  
  become: true
  
  

  vars:
    source_file: /Users/julius/ansible/index.html
    destin_file: //var/www/html/

  tasks:
    - name: "say hello to remote server"
      ping:
    - name: "Lets check OS"
      debug: var=ansible_os_family
    - name: "Lets check ip v4 addr"
      shell: ip addr
      register: result
    - debug:
        msg: "{{ result.stdout_lines }}"
#Testing and getting info about our host 


    - name: "Installing apache"
      apt: name=apache2 state=latest
# Installing apache

    - name: Adding html file to remote hosts
      copy: src={{ source_file }} dest={{ destin_file }} mode=0555
      notify: Restart Apache 
# Copy source file to remote host



  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted 
